package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The command owns the reporting and the write decision; the pipeline itself is
// covered by internal/patternsynth. These tests pin the two things only the
// command can get wrong: --dry-run must not touch the filesystem, and the
// --against thresholds must decide the exit status.

func TestPatternSynth_DryRunReportsAndWritesNothing(t *testing.T) {
	out := filepath.Join(t.TempDir(), "router.yaml")
	stdout := runSynth(t, map[string]string{
		"--package": "github.com/example/orion/router",
		"--corpus":  filepath.Join("..", "..", "internal", "patternsynth", "testdata", "corpus"),
		"--out":     out,
	}, "--dry-run")

	for _, want := range []string{
		"accept  router_get_route",
		"accept  router_route_group",
		"REJECT  router_setlimit",
		"reason: no_extractable_capture",
		"(dry run, not written)",
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("report is missing %q:\n%s", want, stdout)
		}
	}
	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Errorf("--dry-run wrote %s", out)
	}
}

func TestPatternSynth_WritesSurvivors(t *testing.T) {
	out := filepath.Join(t.TempDir(), "nested", "router.yaml")
	runSynth(t, map[string]string{
		"--package": "github.com/example/orion/router",
		"--corpus":  filepath.Join("..", "..", "internal", "patternsynth", "testdata", "corpus"),
		"--out":     out,
	})

	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read written file: %v", err)
	}
	if !bytes.HasPrefix(data, []byte("# Generated by")) {
		t.Errorf("written file lacks the generated header:\n%s", data)
	}
}

// --against is the tier's acceptance criterion wired to an exit status:
// reproducing chi_routes.yaml from its own corpus must succeed, and the same
// run with a zero extra-hit budget must still succeed because it adds none.
func TestPatternSynth_AgainstBaseline(t *testing.T) {
	stdout := runSynth(t, map[string]string{
		"--package":   "github.com/go-chi/chi/v5",
		"--corpus":    filepath.Join("..", "..", "patterns", "go", "chi_routes_test"),
		"--against":   filepath.Join("..", "..", "patterns", "go", "chi_routes.yaml"),
		"--max-extra": "0",
	}, "--dry-run")

	if !strings.Contains(stdout, "missing:        0") {
		t.Errorf("expected every baseline site covered:\n%s", stdout)
	}
}

func TestPatternSynth_FailsWhenBaselineIsNotCovered(t *testing.T) {
	// The corpus holds the routes; the baseline compared against is a pattern
	// file for a different framework, so its sites cannot all be covered.
	err := synthErr(t, map[string]string{
		"--package": "github.com/go-chi/chi/v5",
		"--corpus":  filepath.Join("..", "..", "patterns", "go", "gin_routes_test"),
		"--against": filepath.Join("..", "..", "patterns", "go", "gin_routes.yaml"),
	}, "--dry-run")
	if err == nil {
		t.Fatal("expected a non-nil error when synthesis covers nothing")
	}
}

// runSynth executes the command and returns its stdout, failing on error.
func runSynth(t *testing.T, flags map[string]string, extra ...string) string {
	t.Helper()
	stdout, err := captureSynth(t, flags, extra...)
	if err != nil {
		t.Fatalf("synth: %v\n%s", err, stdout)
	}
	return stdout
}

func synthErr(t *testing.T, flags map[string]string, extra ...string) error {
	t.Helper()
	_, err := captureSynth(t, flags, extra...)
	return err
}

func captureSynth(t *testing.T, flags map[string]string, extra ...string) (string, error) {
	t.Helper()
	cmd := initPatternSynthCmd()
	var args []string
	for k, v := range flags {
		args = append(args, k+"="+v)
	}
	args = append(args, extra...)
	cmd.SetArgs(args)

	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	orig := os.Stdout
	os.Stdout = w
	runErr := cmd.Execute()
	os.Stdout = orig
	w.Close()
	out, _ := io.ReadAll(r)
	r.Close()
	return string(out), runErr
}
