package main

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/lordsonvimal/polyflow/internal/evidence"
	"github.com/lordsonvimal/polyflow/internal/meta"
)

var rulesCmd = &cobra.Command{
	Use:   "rules",
	Short: "Manage contract rules (promote proposals, list custom rules)",
}

func init() {
	promoteCmd := &cobra.Command{
		Use:   "promote <proposal.yaml>",
		Short: "Test a proposed rule against its fixture and promote it to the workspace contracts dir",
		Long: `promote loads the rule YAML and its companion fixture JSON (same base name),
runs the contract engine against the fixture nodes, and — on green — moves both
files to the workspace contracts/ and testdata/contracts/ directories.

On red (fixture mismatch), it prints the diff and refuses. This ensures every
promoted rule has a passing test fixture before it becomes active.

The proposal YAML and fixture JSON are normally generated by 'polyflow doctor --propose'.`,
		Args: cobra.ExactArgs(1),
		RunE: runRulesPromote,
	}
	rulesCmd.AddCommand(promoteCmd)
}

func runRulesPromote(cmd *cobra.Command, args []string) error {
	proposalPath := args[0]
	wsDir := filepath.Dir(meta.ConfigFile)
	if wsDir == "." {
		wsDir, _ = filepath.Abs(".")
	}

	result, err := evidence.RunPromotion(proposalPath, wsDir)
	if err != nil {
		return err
	}

	if result.Diff != "" {
		fmt.Println("Promotion refused — fixture does not pass with the proposed rule.")
		fmt.Println()
		fmt.Println(result.Diff)
		fmt.Println("Edit the proposal YAML (node types, key fields) until the fixture passes.")
		return fmt.Errorf("fixture mismatch")
	}

	fmt.Printf("  Rule     → %s\n", result.RuleDest)
	fmt.Printf("  Fixture  → %s\n", result.FixtureDest)
	fmt.Printf("Promoted. Run 'polyflow index' to activate the new rule.\n")
	return nil
}
