// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: sdk/linkplugin/proto/linkplugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LinkPlugin_Handshake_FullMethodName = "/linkplugin.LinkPlugin/Handshake"
	LinkPlugin_Requires_FullMethodName  = "/linkplugin.LinkPlugin/Requires"
	LinkPlugin_Link_FullMethodName      = "/linkplugin.LinkPlugin/Link"
	LinkPlugin_Reconcile_FullMethodName = "/linkplugin.LinkPlugin/Reconcile"
)

// LinkPluginClient is the client API for LinkPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LinkPlugin is the core->plugin direction: core drives Handshake once,
// then Requires/Link/Reconcile per docs/linker-plugin-architecture-plan.md's
// load sequence.
type LinkPluginClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	Requires(ctx context.Context, in *RequiresRequest, opts ...grpc.CallOption) (*RequiresResponse, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
}

type linkPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkPluginClient(cc grpc.ClientConnInterface) LinkPluginClient {
	return &linkPluginClient{cc}
}

func (c *linkPluginClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, LinkPlugin_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkPluginClient) Requires(ctx context.Context, in *RequiresRequest, opts ...grpc.CallOption) (*RequiresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequiresResponse)
	err := c.cc.Invoke(ctx, LinkPlugin_Requires_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkPluginClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, LinkPlugin_Link_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkPluginClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, LinkPlugin_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkPluginServer is the server API for LinkPlugin service.
// All implementations must embed UnimplementedLinkPluginServer
// for forward compatibility.
//
// LinkPlugin is the core->plugin direction: core drives Handshake once,
// then Requires/Link/Reconcile per docs/linker-plugin-architecture-plan.md's
// load sequence.
type LinkPluginServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	Requires(context.Context, *RequiresRequest) (*RequiresResponse, error)
	Link(context.Context, *LinkRequest) (*LinkResponse, error)
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error)
	mustEmbedUnimplementedLinkPluginServer()
}

// UnimplementedLinkPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinkPluginServer struct{}

func (UnimplementedLinkPluginServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedLinkPluginServer) Requires(context.Context, *RequiresRequest) (*RequiresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Requires not implemented")
}
func (UnimplementedLinkPluginServer) Link(context.Context, *LinkRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Link not implemented")
}
func (UnimplementedLinkPluginServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedLinkPluginServer) mustEmbedUnimplementedLinkPluginServer() {}
func (UnimplementedLinkPluginServer) testEmbeddedByValue()                    {}

// UnsafeLinkPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkPluginServer will
// result in compilation errors.
type UnsafeLinkPluginServer interface {
	mustEmbedUnimplementedLinkPluginServer()
}

func RegisterLinkPluginServer(s grpc.ServiceRegistrar, srv LinkPluginServer) {
	// If the following call panics, it indicates UnimplementedLinkPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LinkPlugin_ServiceDesc, srv)
}

func _LinkPlugin_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkPluginServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkPlugin_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkPluginServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkPlugin_Requires_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequiresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkPluginServer).Requires(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkPlugin_Requires_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkPluginServer).Requires(ctx, req.(*RequiresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkPlugin_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkPluginServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkPlugin_Link_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkPluginServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkPlugin_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkPluginServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkPlugin_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkPluginServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkPlugin_ServiceDesc is the grpc.ServiceDesc for LinkPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkplugin.LinkPlugin",
	HandlerType: (*LinkPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _LinkPlugin_Handshake_Handler,
		},
		{
			MethodName: "Requires",
			Handler:    _LinkPlugin_Requires_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _LinkPlugin_Link_Handler,
		},
		{
			MethodName: "Reconcile",
			Handler:    _LinkPlugin_Reconcile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/linkplugin/proto/linkplugin.proto",
}

const (
	Capabilities_ContainmentBulkResolve_FullMethodName = "/linkplugin.Capabilities/ContainmentBulkResolve"
	Capabilities_SymbolBulkResolve_FullMethodName      = "/linkplugin.Capabilities/SymbolBulkResolve"
	Capabilities_KeyLedgerBulkResolve_FullMethodName   = "/linkplugin.Capabilities/KeyLedgerBulkResolve"
)

// CapabilitiesClient is the client API for Capabilities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Capabilities is the plugin->core callback direction: a plugin component
// that declared containment/symbol_resolver/dynamic_key_ledger in Requires()
// dials back over the GRPCBroker connection named by LinkRequest.broker_id
// to reach these bulk-query implementations, backed by core's existing
// in-process indexes (internal/pluginloader/capabilities.go). Every method
// is bulk (files []string in, one response), never per-node — see
// docs/linker-plugin-architecture-plan.md's Performance section: the
// interface shape is the batching-enforcement mechanism, not a lint rule.
type CapabilitiesClient interface {
	ContainmentBulkResolve(ctx context.Context, in *BulkResolveRequest, opts ...grpc.CallOption) (*BulkResolveResponse, error)
	SymbolBulkResolve(ctx context.Context, in *BulkResolveRequest, opts ...grpc.CallOption) (*BulkResolveResponse, error)
	KeyLedgerBulkResolve(ctx context.Context, in *BulkResolveRequest, opts ...grpc.CallOption) (*BulkResolveResponse, error)
}

type capabilitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilitiesClient(cc grpc.ClientConnInterface) CapabilitiesClient {
	return &capabilitiesClient{cc}
}

func (c *capabilitiesClient) ContainmentBulkResolve(ctx context.Context, in *BulkResolveRequest, opts ...grpc.CallOption) (*BulkResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResolveResponse)
	err := c.cc.Invoke(ctx, Capabilities_ContainmentBulkResolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilitiesClient) SymbolBulkResolve(ctx context.Context, in *BulkResolveRequest, opts ...grpc.CallOption) (*BulkResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResolveResponse)
	err := c.cc.Invoke(ctx, Capabilities_SymbolBulkResolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilitiesClient) KeyLedgerBulkResolve(ctx context.Context, in *BulkResolveRequest, opts ...grpc.CallOption) (*BulkResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResolveResponse)
	err := c.cc.Invoke(ctx, Capabilities_KeyLedgerBulkResolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilitiesServer is the server API for Capabilities service.
// All implementations must embed UnimplementedCapabilitiesServer
// for forward compatibility.
//
// Capabilities is the plugin->core callback direction: a plugin component
// that declared containment/symbol_resolver/dynamic_key_ledger in Requires()
// dials back over the GRPCBroker connection named by LinkRequest.broker_id
// to reach these bulk-query implementations, backed by core's existing
// in-process indexes (internal/pluginloader/capabilities.go). Every method
// is bulk (files []string in, one response), never per-node — see
// docs/linker-plugin-architecture-plan.md's Performance section: the
// interface shape is the batching-enforcement mechanism, not a lint rule.
type CapabilitiesServer interface {
	ContainmentBulkResolve(context.Context, *BulkResolveRequest) (*BulkResolveResponse, error)
	SymbolBulkResolve(context.Context, *BulkResolveRequest) (*BulkResolveResponse, error)
	KeyLedgerBulkResolve(context.Context, *BulkResolveRequest) (*BulkResolveResponse, error)
	mustEmbedUnimplementedCapabilitiesServer()
}

// UnimplementedCapabilitiesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilitiesServer struct{}

func (UnimplementedCapabilitiesServer) ContainmentBulkResolve(context.Context, *BulkResolveRequest) (*BulkResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContainmentBulkResolve not implemented")
}
func (UnimplementedCapabilitiesServer) SymbolBulkResolve(context.Context, *BulkResolveRequest) (*BulkResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SymbolBulkResolve not implemented")
}
func (UnimplementedCapabilitiesServer) KeyLedgerBulkResolve(context.Context, *BulkResolveRequest) (*BulkResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyLedgerBulkResolve not implemented")
}
func (UnimplementedCapabilitiesServer) mustEmbedUnimplementedCapabilitiesServer() {}
func (UnimplementedCapabilitiesServer) testEmbeddedByValue()                      {}

// UnsafeCapabilitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilitiesServer will
// result in compilation errors.
type UnsafeCapabilitiesServer interface {
	mustEmbedUnimplementedCapabilitiesServer()
}

func RegisterCapabilitiesServer(s grpc.ServiceRegistrar, srv CapabilitiesServer) {
	// If the following call panics, it indicates UnimplementedCapabilitiesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Capabilities_ServiceDesc, srv)
}

func _Capabilities_ContainmentBulkResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilitiesServer).ContainmentBulkResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capabilities_ContainmentBulkResolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilitiesServer).ContainmentBulkResolve(ctx, req.(*BulkResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capabilities_SymbolBulkResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilitiesServer).SymbolBulkResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capabilities_SymbolBulkResolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilitiesServer).SymbolBulkResolve(ctx, req.(*BulkResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capabilities_KeyLedgerBulkResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilitiesServer).KeyLedgerBulkResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capabilities_KeyLedgerBulkResolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilitiesServer).KeyLedgerBulkResolve(ctx, req.(*BulkResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Capabilities_ServiceDesc is the grpc.ServiceDesc for Capabilities service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capabilities_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkplugin.Capabilities",
	HandlerType: (*CapabilitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainmentBulkResolve",
			Handler:    _Capabilities_ContainmentBulkResolve_Handler,
		},
		{
			MethodName: "SymbolBulkResolve",
			Handler:    _Capabilities_SymbolBulkResolve_Handler,
		},
		{
			MethodName: "KeyLedgerBulkResolve",
			Handler:    _Capabilities_KeyLedgerBulkResolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/linkplugin/proto/linkplugin.proto",
}
