// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: sdk/linkplugin/proto/linkplugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node mirrors internal/graph/model.go's Node. The SDK vendors this shape
// (sdk/linkplugin/graph) rather than importing internal/graph directly, so
// core can evolve its internal representation without breaking the wire
// contract — this .proto only changes on a protocol_version bump.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	File          string                 `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	Line          int64                  `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	EndLine       int64                  `protobuf:"varint,7,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Language      string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,9,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Node) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Node) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Node) GetEndLine() int64 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Node) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Node) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Confidence    string                 `protobuf:"bytes,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	ObservedAt    int64                  `protobuf:"varint,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	CodeFile      string                 `protobuf:"bytes,5,opt,name=code_file,json=codeFile,proto3" json:"code_file,omitempty"`
	CodeFunc      string                 `protobuf:"bytes,6,opt,name=code_func,json=codeFunc,proto3" json:"code_func,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRef) Reset() {
	*x = SourceRef{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRef) ProtoMessage() {}

func (x *SourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRef.ProtoReflect.Descriptor instead.
func (*SourceRef) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{1}
}

func (x *SourceRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SourceRef) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *SourceRef) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *SourceRef) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

func (x *SourceRef) GetCodeFile() string {
	if x != nil {
		return x.CodeFile
	}
	return ""
}

func (x *SourceRef) GetCodeFunc() string {
	if x != nil {
		return x.CodeFunc
	}
	return ""
}

type Edge struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                  string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Type                string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Label               string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Confidence          string                 `protobuf:"bytes,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Method              string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	Path                string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Meta                map[string]string      `protobuf:"bytes,9,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sources             []*SourceRef           `protobuf:"bytes,10,rep,name=sources,proto3" json:"sources,omitempty"`
	VerificationState   string                 `protobuf:"bytes,11,opt,name=verification_state,json=verificationState,proto3" json:"verification_state,omitempty"`
	VerifiedGranularity string                 `protobuf:"bytes,12,opt,name=verified_granularity,json=verifiedGranularity,proto3" json:"verified_granularity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{2}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Edge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Edge) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *Edge) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Edge) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Edge) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Edge) GetSources() []*SourceRef {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Edge) GetVerificationState() string {
	if x != nil {
		return x.VerificationState
	}
	return ""
}

func (x *Edge) GetVerifiedGranularity() string {
	if x != nil {
		return x.VerifiedGranularity
	}
	return ""
}

type UnresolvedRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line          int64                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Targets       string                 `protobuf:"bytes,6,opt,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedRef) Reset() {
	*x = UnresolvedRef{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedRef) ProtoMessage() {}

func (x *UnresolvedRef) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedRef.ProtoReflect.Descriptor instead.
func (*UnresolvedRef) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{3}
}

func (x *UnresolvedRef) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UnresolvedRef) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *UnresolvedRef) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *UnresolvedRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnresolvedRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UnresolvedRef) GetTargets() string {
	if x != nil {
		return x.Targets
	}
	return ""
}

// Result is a plugin's Link/Reconcile output — see linkplugin.Result in
// sdk/linkplugin/plugin.go. Retract mirrors DropResolvedRefs
// (internal/linker/amqp_handshake.go)'s in-process precedent.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*Edge                `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	Unresolved    []*UnresolvedRef       `protobuf:"bytes,2,rep,name=unresolved,proto3" json:"unresolved,omitempty"`
	Retract       []string               `protobuf:"bytes,3,rep,name=retract,proto3" json:"retract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Result) GetUnresolved() []*UnresolvedRef {
	if x != nil {
		return x.Unresolved
	}
	return nil
}

func (x *Result) GetRetract() []string {
	if x != nil {
		return x.Retract
	}
	return nil
}

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{6}
}

func (x *HandshakeResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequiresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiresRequest) Reset() {
	*x = RequiresRequest{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiresRequest) ProtoMessage() {}

func (x *RequiresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiresRequest.ProtoReflect.Descriptor instead.
func (*RequiresRequest) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{7}
}

func (x *RequiresRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

// capabilities values are the wire form of linkplugin.Capability
// ("containment" | "symbol_resolver" | "dynamic_key_ledger").
type RequiresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiresResponse) Reset() {
	*x = RequiresResponse{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiresResponse) ProtoMessage() {}

func (x *RequiresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiresResponse.ProtoReflect.Descriptor instead.
func (*RequiresResponse) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{8}
}

func (x *RequiresResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// LinkRequest is one batched Link() call: one component, one service, one
// file-batch — see docs/linker-plugin-architecture-plan.md's Performance
// section on why batching is load-bearing, not optional. broker_id is a
// hashicorp/go-plugin GRPCBroker connection ID the plugin dials back on to
// reach the bulk-query capability services this component declared in
// capabilities (0 = no capabilities wired, no dial-back expected).
type LinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Files         []string               `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	BrokerId      uint32                 `protobuf:"varint,5,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{9}
}

func (x *LinkRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *LinkRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LinkRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *LinkRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LinkRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *LinkRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{10}
}

func (x *LinkResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

// ReconcileRequest mirrors linkplugin.ReconcileContext: this plugin's own
// per-component results pooled across every service, plus read-only
// visibility into every other plugin's (and core's built-in linkers') own
// results, keyed by name.
type ReconcileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ComponentResults map[string]*Result     `protobuf:"bytes,1,rep,name=component_results,json=componentResults,proto3" json:"component_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllResults       map[string]*Result     `protobuf:"bytes,2,rep,name=all_results,json=allResults,proto3" json:"all_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{11}
}

func (x *ReconcileRequest) GetComponentResults() map[string]*Result {
	if x != nil {
		return x.ComponentResults
	}
	return nil
}

func (x *ReconcileRequest) GetAllResults() map[string]*Result {
	if x != nil {
		return x.AllResults
	}
	return nil
}

type ReconcileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{12}
}

func (x *ReconcileResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type BulkResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResolveRequest) Reset() {
	*x = BulkResolveRequest{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResolveRequest) ProtoMessage() {}

func (x *BulkResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResolveRequest.ProtoReflect.Descriptor instead.
func (*BulkResolveRequest) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{13}
}

func (x *BulkResolveRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// Scope is one bulk-query capability's answer for one file — a class/module
// containment scope (ContainmentIndex), a resolved symbol's defining scope
// (SymbolResolver), or a dynamic-key ledger entry (DynamicKeyLedger). The
// three capabilities share this shape because all three are, structurally,
// "given a file, name a scope/definition site."
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{14}
}

func (x *Scope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Scope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scope) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type BulkResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        map[string]*Scope      `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResolveResponse) Reset() {
	*x = BulkResolveResponse{}
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResolveResponse) ProtoMessage() {}

func (x *BulkResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_linkplugin_proto_linkplugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResolveResponse.ProtoReflect.Descriptor instead.
func (*BulkResolveResponse) Descriptor() ([]byte, []int) {
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP(), []int{15}
}

func (x *BulkResolveResponse) GetScopes() map[string]*Scope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_sdk_linkplugin_proto_linkplugin_proto protoreflect.FileDescriptor

const file_sdk_linkplugin_proto_linkplugin_proto_rawDesc = "" +
	"\n" +
	"%sdk/linkplugin/proto/linkplugin.proto\x12\n" +
	"linkplugin\"\xa2\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x12\n" +
	"\x04file\x18\x05 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x06 \x01(\x03R\x04line\x12\x19\n" +
	"\bend_line\x18\a \x01(\x03R\aendLine\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12.\n" +
	"\x04meta\x18\t \x03(\v2\x1a.linkplugin.Node.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\tSourceRef\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\tR\n" +
	"confidence\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x1f\n" +
	"\vobserved_at\x18\x04 \x01(\x03R\n" +
	"observedAt\x12\x1b\n" +
	"\tcode_file\x18\x05 \x01(\tR\bcodeFile\x12\x1b\n" +
	"\tcode_func\x18\x06 \x01(\tR\bcodeFunc\"\xac\x03\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\tR\n" +
	"confidence\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12.\n" +
	"\x04meta\x18\t \x03(\v2\x1a.linkplugin.Edge.MetaEntryR\x04meta\x12/\n" +
	"\asources\x18\n" +
	" \x03(\v2\x15.linkplugin.SourceRefR\asources\x12-\n" +
	"\x12verification_state\x18\v \x01(\tR\x11verificationState\x121\n" +
	"\x14verified_granularity\x18\f \x01(\tR\x13verifiedGranularity\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\rUnresolvedRef\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x03R\x04line\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\atargets\x18\x06 \x01(\tR\atargets\"\x85\x01\n" +
	"\x06Result\x12&\n" +
	"\x05edges\x18\x01 \x03(\v2\x10.linkplugin.EdgeR\x05edges\x129\n" +
	"\n" +
	"unresolved\x18\x02 \x03(\v2\x19.linkplugin.UnresolvedRefR\n" +
	"unresolved\x12\x18\n" +
	"\aretract\x18\x03 \x03(\tR\aretract\"=\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\"R\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x0fRequiresRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\"6\n" +
	"\x10RequiresResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"\xc9\x01\n" +
	"\vLinkRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\x12&\n" +
	"\x05nodes\x18\x04 \x03(\v2\x10.linkplugin.NodeR\x05nodes\x12\x1b\n" +
	"\tbroker_id\x18\x05 \x01(\rR\bbrokerId\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\":\n" +
	"\fLinkResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.linkplugin.ResultR\x06result\"\xee\x02\n" +
	"\x10ReconcileRequest\x12_\n" +
	"\x11component_results\x18\x01 \x03(\v22.linkplugin.ReconcileRequest.ComponentResultsEntryR\x10componentResults\x12M\n" +
	"\vall_results\x18\x02 \x03(\v2,.linkplugin.ReconcileRequest.AllResultsEntryR\n" +
	"allResults\x1aW\n" +
	"\x15ComponentResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.linkplugin.ResultR\x05value:\x028\x01\x1aQ\n" +
	"\x0fAllResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.linkplugin.ResultR\x05value:\x028\x01\"?\n" +
	"\x11ReconcileResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.linkplugin.ResultR\x06result\"*\n" +
	"\x12BulkResolveRequest\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\"A\n" +
	"\x05Scope\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\xa8\x01\n" +
	"\x13BulkResolveResponse\x12C\n" +
	"\x06scopes\x18\x01 \x03(\v2+.linkplugin.BulkResolveResponse.ScopesEntryR\x06scopes\x1aL\n" +
	"\vScopesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.linkplugin.ScopeR\x05value:\x028\x012\xa2\x02\n" +
	"\n" +
	"LinkPlugin\x12H\n" +
	"\tHandshake\x12\x1c.linkplugin.HandshakeRequest\x1a\x1d.linkplugin.HandshakeResponse\x12E\n" +
	"\bRequires\x12\x1b.linkplugin.RequiresRequest\x1a\x1c.linkplugin.RequiresResponse\x129\n" +
	"\x04Link\x12\x17.linkplugin.LinkRequest\x1a\x18.linkplugin.LinkResponse\x12H\n" +
	"\tReconcile\x12\x1c.linkplugin.ReconcileRequest\x1a\x1d.linkplugin.ReconcileResponse2\x98\x02\n" +
	"\fCapabilities\x12Y\n" +
	"\x16ContainmentBulkResolve\x12\x1e.linkplugin.BulkResolveRequest\x1a\x1f.linkplugin.BulkResolveResponse\x12T\n" +
	"\x11SymbolBulkResolve\x12\x1e.linkplugin.BulkResolveRequest\x1a\x1f.linkplugin.BulkResolveResponse\x12W\n" +
	"\x14KeyLedgerBulkResolve\x12\x1e.linkplugin.BulkResolveRequest\x1a\x1f.linkplugin.BulkResolveResponseB7Z5github.com/lordsonvimal/polyflow/sdk/linkplugin/protob\x06proto3"

var (
	file_sdk_linkplugin_proto_linkplugin_proto_rawDescOnce sync.Once
	file_sdk_linkplugin_proto_linkplugin_proto_rawDescData []byte
)

func file_sdk_linkplugin_proto_linkplugin_proto_rawDescGZIP() []byte {
	file_sdk_linkplugin_proto_linkplugin_proto_rawDescOnce.Do(func() {
		file_sdk_linkplugin_proto_linkplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_linkplugin_proto_linkplugin_proto_rawDesc), len(file_sdk_linkplugin_proto_linkplugin_proto_rawDesc)))
	})
	return file_sdk_linkplugin_proto_linkplugin_proto_rawDescData
}

var file_sdk_linkplugin_proto_linkplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sdk_linkplugin_proto_linkplugin_proto_goTypes = []any{
	(*Node)(nil),                // 0: linkplugin.Node
	(*SourceRef)(nil),           // 1: linkplugin.SourceRef
	(*Edge)(nil),                // 2: linkplugin.Edge
	(*UnresolvedRef)(nil),       // 3: linkplugin.UnresolvedRef
	(*Result)(nil),              // 4: linkplugin.Result
	(*HandshakeRequest)(nil),    // 5: linkplugin.HandshakeRequest
	(*HandshakeResponse)(nil),   // 6: linkplugin.HandshakeResponse
	(*RequiresRequest)(nil),     // 7: linkplugin.RequiresRequest
	(*RequiresResponse)(nil),    // 8: linkplugin.RequiresResponse
	(*LinkRequest)(nil),         // 9: linkplugin.LinkRequest
	(*LinkResponse)(nil),        // 10: linkplugin.LinkResponse
	(*ReconcileRequest)(nil),    // 11: linkplugin.ReconcileRequest
	(*ReconcileResponse)(nil),   // 12: linkplugin.ReconcileResponse
	(*BulkResolveRequest)(nil),  // 13: linkplugin.BulkResolveRequest
	(*Scope)(nil),               // 14: linkplugin.Scope
	(*BulkResolveResponse)(nil), // 15: linkplugin.BulkResolveResponse
	nil,                         // 16: linkplugin.Node.MetaEntry
	nil,                         // 17: linkplugin.Edge.MetaEntry
	nil,                         // 18: linkplugin.ReconcileRequest.ComponentResultsEntry
	nil,                         // 19: linkplugin.ReconcileRequest.AllResultsEntry
	nil,                         // 20: linkplugin.BulkResolveResponse.ScopesEntry
}
var file_sdk_linkplugin_proto_linkplugin_proto_depIdxs = []int32{
	16, // 0: linkplugin.Node.meta:type_name -> linkplugin.Node.MetaEntry
	17, // 1: linkplugin.Edge.meta:type_name -> linkplugin.Edge.MetaEntry
	1,  // 2: linkplugin.Edge.sources:type_name -> linkplugin.SourceRef
	2,  // 3: linkplugin.Result.edges:type_name -> linkplugin.Edge
	3,  // 4: linkplugin.Result.unresolved:type_name -> linkplugin.UnresolvedRef
	0,  // 5: linkplugin.LinkRequest.nodes:type_name -> linkplugin.Node
	4,  // 6: linkplugin.LinkResponse.result:type_name -> linkplugin.Result
	18, // 7: linkplugin.ReconcileRequest.component_results:type_name -> linkplugin.ReconcileRequest.ComponentResultsEntry
	19, // 8: linkplugin.ReconcileRequest.all_results:type_name -> linkplugin.ReconcileRequest.AllResultsEntry
	4,  // 9: linkplugin.ReconcileResponse.result:type_name -> linkplugin.Result
	20, // 10: linkplugin.BulkResolveResponse.scopes:type_name -> linkplugin.BulkResolveResponse.ScopesEntry
	4,  // 11: linkplugin.ReconcileRequest.ComponentResultsEntry.value:type_name -> linkplugin.Result
	4,  // 12: linkplugin.ReconcileRequest.AllResultsEntry.value:type_name -> linkplugin.Result
	14, // 13: linkplugin.BulkResolveResponse.ScopesEntry.value:type_name -> linkplugin.Scope
	5,  // 14: linkplugin.LinkPlugin.Handshake:input_type -> linkplugin.HandshakeRequest
	7,  // 15: linkplugin.LinkPlugin.Requires:input_type -> linkplugin.RequiresRequest
	9,  // 16: linkplugin.LinkPlugin.Link:input_type -> linkplugin.LinkRequest
	11, // 17: linkplugin.LinkPlugin.Reconcile:input_type -> linkplugin.ReconcileRequest
	13, // 18: linkplugin.Capabilities.ContainmentBulkResolve:input_type -> linkplugin.BulkResolveRequest
	13, // 19: linkplugin.Capabilities.SymbolBulkResolve:input_type -> linkplugin.BulkResolveRequest
	13, // 20: linkplugin.Capabilities.KeyLedgerBulkResolve:input_type -> linkplugin.BulkResolveRequest
	6,  // 21: linkplugin.LinkPlugin.Handshake:output_type -> linkplugin.HandshakeResponse
	8,  // 22: linkplugin.LinkPlugin.Requires:output_type -> linkplugin.RequiresResponse
	10, // 23: linkplugin.LinkPlugin.Link:output_type -> linkplugin.LinkResponse
	12, // 24: linkplugin.LinkPlugin.Reconcile:output_type -> linkplugin.ReconcileResponse
	15, // 25: linkplugin.Capabilities.ContainmentBulkResolve:output_type -> linkplugin.BulkResolveResponse
	15, // 26: linkplugin.Capabilities.SymbolBulkResolve:output_type -> linkplugin.BulkResolveResponse
	15, // 27: linkplugin.Capabilities.KeyLedgerBulkResolve:output_type -> linkplugin.BulkResolveResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sdk_linkplugin_proto_linkplugin_proto_init() }
func file_sdk_linkplugin_proto_linkplugin_proto_init() {
	if File_sdk_linkplugin_proto_linkplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_linkplugin_proto_linkplugin_proto_rawDesc), len(file_sdk_linkplugin_proto_linkplugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sdk_linkplugin_proto_linkplugin_proto_goTypes,
		DependencyIndexes: file_sdk_linkplugin_proto_linkplugin_proto_depIdxs,
		MessageInfos:      file_sdk_linkplugin_proto_linkplugin_proto_msgTypes,
	}.Build()
	File_sdk_linkplugin_proto_linkplugin_proto = out.File
	file_sdk_linkplugin_proto_linkplugin_proto_goTypes = nil
	file_sdk_linkplugin_proto_linkplugin_proto_depIdxs = nil
}
