package patternsynth

import (
	"fmt"
	"strings"

	"github.com/lordsonvimal/polyflow/internal/patterns"
)

// GeneratedMarker is the first line of every synthesized pattern file. Review
// tooling and humans both key off it, so it is a constant, not a format string.
const GeneratedMarker = "# Generated by `polyflow pattern synth` — do not edit by hand."

// Render writes the survivors as a pattern file.
//
// It is hand-rendered rather than yaml.Marshal'd for two reasons: the header
// carries the provenance a marshaller has nowhere to put, and the query blocks
// must come out in the same block-scalar shape as the hand-written files so a
// synthesized file and a reviewed one read identically in a diff.
//
// The header records the package, the corpus and the corpus SHA. A synthesized
// pattern nobody can trace back to the evidence that justified it is
// unreviewable, and synthesis makes producing those cheap. There is no
// timestamp on purpose: the output must be byte-identical across two runs over
// the same corpus, or nobody can tell a re-synthesis from a change.
func Render(pats []patterns.Pattern, opts Options, corpusSHA string) string {
	var b strings.Builder
	b.WriteString(GeneratedMarker + "\n")
	b.WriteString("# Re-synthesize with:\n")
	fmt.Fprintf(&b, "#   polyflow pattern synth --package %s --corpus %s\n", opts.Package, opts.Corpus)
	fmt.Fprintf(&b, "# package: %s\n", opts.Package)
	fmt.Fprintf(&b, "# corpus:  %s\n", opts.Corpus)
	fmt.Fprintf(&b, "# corpus-sha: %s\n", corpusSHA)
	fmt.Fprintf(&b, "# proposer: %s\n", proposerName(opts))
	b.WriteString("#\n")
	b.WriteString("# Every capture role below is inferred, not reviewed. Check the roles\n")
	b.WriteString("# before this file is trusted, and add the fixture directory\n")
	fmt.Fprintf(&b, "# patterns/%s/%s_test/ that TestPatternFixtures requires.\n", opts.Language, opts.Slug())

	fmt.Fprintf(&b, "language: %s\n", opts.Language)
	b.WriteString("version: \"1\"\n")
	if opts.Package != "" {
		// The package gate is free provenance *and* free precision: these
		// patterns only ever ran against files importing this package, so
		// activating them for a service that does not depend on it can only
		// produce false positives.
		fmt.Fprintf(&b, "package: %s\n", opts.Package)
	}
	b.WriteString("patterns:\n")
	for _, p := range pats {
		fmt.Fprintf(&b, "  - name: %s\n", p.Name)
		b.WriteString("    query: |\n")
		for _, line := range strings.Split(strings.TrimRight(p.Query, "\n"), "\n") {
			if line == "" {
				b.WriteString("\n")
				continue
			}
			fmt.Fprintf(&b, "      %s\n", line)
		}
		if len(p.Captures) > 0 {
			b.WriteString("    captures:\n")
			for _, c := range p.Captures {
				fmt.Fprintf(&b, "      - name: %s\n", c.Name)
				fmt.Fprintf(&b, "        role: %s\n", roleOrTODO(c.Role))
			}
		}
	}
	return b.String()
}

func proposerName(opts Options) string {
	if opts.Proposer == nil {
		return TemplateProposer{}.Name()
	}
	return opts.Proposer.Name()
}

// roleOrTODO keeps an un-inferred role visible. An empty role would read as
// "reviewed and deliberately blank"; TODO reads as what it is.
func roleOrTODO(role string) string {
	if role == "" {
		return "TODO"
	}
	return role
}
